server:
  port: 8003
eureka:
  instance:
    instance-id: dept-8001.com      #在信息列表时显示主机名称
    prefer-ip-address: true         #访问路径变为IP地址
#    lease-expiration-duration-in-seconds: 5  #设置心跳间隔周期（默认是90秒）大部分情况下不需要修改
#    lease-renewal-interval-in-seconds: 2    #设置心跳的时间间隔（默认是30秒）大部分情况下不需要修改
  client:
    service-url:
      defaultZone: http://root:root@localhost:7001/eureka/  # , http://root:root@localhost:7002/eureka/ , http://root:root@localhost:7003/eureka/  #互相注册实现HA机制
info:
  app.name: hy-microcloud
  company.name: www.hengyue.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: mictocloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hykj_dept_8001
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dbcp2:
      max-idle: 10
      min-idle: 2
      initial-size: 2
      max-wait-millis: 200
mybatis:
  type-aliases-package: com.hengyue.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml
